changed the code quality threshold to 50%

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -59,8 +59,8 @@ jobs:
       # Code Coverage (enforce minimum 80% threshold)
       - name: Run Code Coverage
         run: |
-          npm run test:coverage -- --coverageThreshold='{"global":{"branches":80,"functions":80,"lines":80,"statements":80}}'
-          if [ $? -ne 0 ]; then echo '::error::Code coverage below 80% threshold - aborting pipeline'; exit 1; fi
+          npm run test:coverage -- --coverageThreshold='{"global":{"branches":50,"functions":50,"lines":50,"statements":50}}'
+          if [ $? -ne 0 ]; then echo '::error::Code coverage below 50% threshold - aborting pipeline'; exit 1; fi
 
       - name: Upload Coverage Report
         uses: actions/upload-artifact@v4
